2021-02-27 20:20:04.409 - INFO - 18002 - azureml.train.automl.automlconfig._start_execution:208 - Submitting remote.
2021-02-27 22:14:05.658 - INFO - 18002 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-02-27 22:14:05.704 - INFO - 18002 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-02-27 22:14:05.720 - INFO - 18002 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2021-02-27 22:14:05.853 - INFO - 18002 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=132.99[ms]
2021-02-27 22:14:05.854 - INFO - 18002 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=149.38[ms]
2021-02-27 22:14:05.860 - INFO - 18002 - azureml.train.automl._model_download_utilities._log_activity:54 - ActivityStarted: DownloadModel
2021-02-27 22:14:17.210 - INFO - 18002 - azureml.automl.runtime.distributed.utilities.horovod_initialized:58 - Horovod not found in current environment. Distribution via Horovod will be disabled.
2021-02-27 22:14:19.981 - INFO - 18002 - azureml.automl.runtime.featurization.data_transformer.__init__:184 - Feature sweeping enabled: False
2021-02-27 22:14:19.981 - INFO - 18002 - azureml.automl.runtime.featurization.data_transformer.__init__:185 - Feature sweeping timeout: 86400
2021-02-27 22:14:21.361 - INFO - 18002 - azureml.train.automl._model_download_utilities._log_activity:92 - ActivityCompleted: Activity=DownloadModel, HowEnded=Success, Duration=15500.72[ms]
2021-02-27 22:14:21.361 - INFO - 18002 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=15703.33[ms]
2021-02-28 00:15:05.022 - INFO - 18002 - azureml.train.automl.automlconfig._start_execution:208 - Submitting remote.
2021-03-01 20:02:17.388 - INFO - 5948 - azureml.train.automl.automlconfig._start_execution:211 - Submitting remote.
2021-03-01 20:51:21.584 - INFO - 5948 - azureml.train.automl.automlconfig._start_execution:211 - Submitting remote.
2021-03-01 21:38:23.796 - INFO - 5948 - azureml.train.automl.automlconfig._start_execution:211 - Submitting remote.
2021-03-01 22:59:08.307 - INFO - 5948 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-03-01 22:59:08.349 - INFO - 5948 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-03-01 22:59:08.354 - INFO - 5948 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2021-03-01 22:59:08.559 - INFO - 5948 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=205.35[ms]
2021-03-01 22:59:08.560 - INFO - 5948 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=210.2[ms]
2021-03-01 22:59:08.575 - INFO - 5948 - azureml.train.automl._model_download_utilities._log_activity:54 - ActivityStarted: DownloadModel
2021-03-01 22:59:20.011 - INFO - 5948 - azureml.automl.runtime.distributed.utilities.horovod_initialized:58 - Horovod not found in current environment. Distribution via Horovod will be disabled.
2021-03-01 22:59:22.855 - INFO - 5948 - azureml.automl.runtime.featurization.data_transformer.__init__:174 - Feature sweeping enabled: False
2021-03-01 22:59:22.855 - INFO - 5948 - azureml.automl.runtime.featurization.data_transformer.__init__:175 - Feature sweeping timeout: 86400
2021-03-01 22:59:24.479 - CRITICAL - 5948 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: Unclassified
Class: AttributeError
Message: /anaconda/envs/azureml_py36/lib/libxgboost.so: undefined symbol: XGBoosterUnserializeFromBuffer
Traceback:
  File "_model_download_utilities.py", line 174, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))

ExceptionTarget: Unspecified
2021-03-01 22:59:24.684 - CRITICAL - 5948 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: Unclassified
Class: AttributeError
Message: /anaconda/envs/azureml_py36/lib/libxgboost.so: undefined symbol: XGBoosterUnserializeFromBuffer
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "_model_download_utilities.py", line 90, in _download_automl_model
    model = _load_automl_model(model_path)
  File "_model_download_utilities.py", line 174, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))

ExceptionTarget: Unspecified
2021-03-01 22:59:24.685 - INFO - 5948 - azureml.train.automl._model_download_utilities._log_activity:92 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=16109.95[ms]
2021-03-01 22:59:24.686 - CRITICAL - 5948 - azureml.train.automl.run.log_traceback:224 - Type: Unclassified
Class: AttributeError
Message: /anaconda/envs/azureml_py36/lib/libxgboost.so: undefined symbol: XGBoosterUnserializeFromBuffer
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 701, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 90, in _download_automl_model
    model = _load_automl_model(model_path)
  File "_model_download_utilities.py", line 174, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))

ExceptionTarget: Unspecified
2021-03-01 22:59:24.686 - INFO - 5948 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=16379.56[ms]
2021-03-01 23:06:14.176 - INFO - 5948 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-03-01 23:06:14.182 - INFO - 5948 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-03-01 23:06:14.194 - INFO - 5948 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2021-03-01 23:06:14.318 - INFO - 5948 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=124.4[ms]
2021-03-01 23:06:14.319 - INFO - 5948 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=136.36[ms]
2021-03-01 23:06:14.320 - INFO - 5948 - azureml.train.automl._model_download_utilities._log_activity:54 - ActivityStarted: DownloadModel
2021-03-01 23:06:15.199 - INFO - 5948 - azureml.automl.runtime.featurization.data_transformer.__init__:174 - Feature sweeping enabled: False
2021-03-01 23:06:15.200 - INFO - 5948 - azureml.automl.runtime.featurization.data_transformer.__init__:175 - Feature sweeping timeout: 86400
2021-03-01 23:06:15.202 - CRITICAL - 5948 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: Unclassified
Class: AttributeError
Message: /anaconda/envs/azureml_py36/lib/libxgboost.so: undefined symbol: XGBoosterUnserializeFromBuffer
Traceback:
  File "_model_download_utilities.py", line 174, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))

ExceptionTarget: Unspecified
2021-03-01 23:06:15.449 - CRITICAL - 5948 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: Unclassified
Class: AttributeError
Message: /anaconda/envs/azureml_py36/lib/libxgboost.so: undefined symbol: XGBoosterUnserializeFromBuffer
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "_model_download_utilities.py", line 90, in _download_automl_model
    model = _load_automl_model(model_path)
  File "_model_download_utilities.py", line 174, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))

ExceptionTarget: Unspecified
2021-03-01 23:06:15.449 - INFO - 5948 - azureml.train.automl._model_download_utilities._log_activity:92 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=1129.59[ms]
2021-03-01 23:06:15.451 - CRITICAL - 5948 - azureml.train.automl.run.log_traceback:224 - Type: Unclassified
Class: AttributeError
Message: /anaconda/envs/azureml_py36/lib/libxgboost.so: undefined symbol: XGBoosterUnserializeFromBuffer
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 701, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 90, in _download_automl_model
    model = _load_automl_model(model_path)
  File "_model_download_utilities.py", line 174, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))

ExceptionTarget: Unspecified
2021-03-01 23:06:15.451 - INFO - 5948 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=1275.49[ms]
2021-03-01 23:07:57.534 - INFO - 5948 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-03-01 23:07:57.542 - INFO - 5948 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-03-01 23:07:57.564 - INFO - 5948 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2021-03-01 23:07:57.718 - INFO - 5948 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=154.31[ms]
2021-03-01 23:07:57.719 - INFO - 5948 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=177.1[ms]
2021-03-01 23:07:57.720 - INFO - 5948 - azureml.train.automl._model_download_utilities._log_activity:54 - ActivityStarted: DownloadModel
2021-03-01 23:07:59.620 - INFO - 5948 - azureml.automl.runtime.featurization.data_transformer.__init__:174 - Feature sweeping enabled: False
2021-03-01 23:07:59.620 - INFO - 5948 - azureml.automl.runtime.featurization.data_transformer.__init__:175 - Feature sweeping timeout: 86400
2021-03-01 23:07:59.622 - CRITICAL - 5948 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: Unclassified
Class: AttributeError
Message: /anaconda/envs/azureml_py36/lib/libxgboost.so: undefined symbol: XGBoosterUnserializeFromBuffer
Traceback:
  File "_model_download_utilities.py", line 174, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))

ExceptionTarget: Unspecified
2021-03-01 23:08:00.644 - CRITICAL - 5948 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: Unclassified
Class: AttributeError
Message: /anaconda/envs/azureml_py36/lib/libxgboost.so: undefined symbol: XGBoosterUnserializeFromBuffer
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "_model_download_utilities.py", line 90, in _download_automl_model
    model = _load_automl_model(model_path)
  File "_model_download_utilities.py", line 174, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))

ExceptionTarget: Unspecified
2021-03-01 23:08:00.644 - INFO - 5948 - azureml.train.automl._model_download_utilities._log_activity:92 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=2924.03[ms]
2021-03-01 23:08:00.645 - CRITICAL - 5948 - azureml.train.automl.run.log_traceback:224 - Type: Unclassified
Class: AttributeError
Message: /anaconda/envs/azureml_py36/lib/libxgboost.so: undefined symbol: XGBoosterUnserializeFromBuffer
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 701, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 90, in _download_automl_model
    model = _load_automl_model(model_path)
  File "_model_download_utilities.py", line 174, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))

ExceptionTarget: Unspecified
2021-03-01 23:08:00.646 - INFO - 5948 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=3111.45[ms]
2021-03-01 23:08:29.093 - INFO - 5948 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-03-01 23:08:29.108 - INFO - 5948 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-03-01 23:08:29.114 - INFO - 5948 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2021-03-01 23:08:29.245 - INFO - 5948 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=130.92[ms]
2021-03-01 23:08:29.245 - INFO - 5948 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=136.74[ms]
2021-03-01 23:08:29.246 - INFO - 5948 - azureml.train.automl._model_download_utilities._log_activity:54 - ActivityStarted: DownloadModel
2021-03-01 23:08:29.927 - INFO - 5948 - azureml.automl.runtime.featurization.data_transformer.__init__:174 - Feature sweeping enabled: False
2021-03-01 23:08:29.927 - INFO - 5948 - azureml.automl.runtime.featurization.data_transformer.__init__:175 - Feature sweeping timeout: 86400
2021-03-01 23:08:29.929 - CRITICAL - 5948 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: Unclassified
Class: AttributeError
Message: /anaconda/envs/azureml_py36/lib/libxgboost.so: undefined symbol: XGBoosterUnserializeFromBuffer
Traceback:
  File "_model_download_utilities.py", line 174, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))

ExceptionTarget: Unspecified
2021-03-01 23:08:30.022 - CRITICAL - 5948 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: Unclassified
Class: AttributeError
Message: /anaconda/envs/azureml_py36/lib/libxgboost.so: undefined symbol: XGBoosterUnserializeFromBuffer
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "_model_download_utilities.py", line 90, in _download_automl_model
    model = _load_automl_model(model_path)
  File "_model_download_utilities.py", line 174, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))

ExceptionTarget: Unspecified
2021-03-01 23:08:30.022 - INFO - 5948 - azureml.train.automl._model_download_utilities._log_activity:92 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=776.12[ms]
2021-03-01 23:08:30.024 - CRITICAL - 5948 - azureml.train.automl.run.log_traceback:224 - Type: Unclassified
Class: AttributeError
Message: /anaconda/envs/azureml_py36/lib/libxgboost.so: undefined symbol: XGBoosterUnserializeFromBuffer
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 701, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 90, in _download_automl_model
    model = _load_automl_model(model_path)
  File "_model_download_utilities.py", line 174, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))

ExceptionTarget: Unspecified
2021-03-01 23:08:30.024 - INFO - 5948 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=931.49[ms]
2021-03-01 23:08:50.966 - INFO - 5948 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-03-01 23:08:50.975 - INFO - 5948 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-03-01 23:08:50.987 - INFO - 5948 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2021-03-01 23:08:51.123 - INFO - 5948 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=135.65[ms]
2021-03-01 23:08:51.123 - INFO - 5948 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=148.41[ms]
2021-03-01 23:08:51.125 - INFO - 5948 - azureml.train.automl._model_download_utilities._log_activity:54 - ActivityStarted: DownloadModel
2021-03-01 23:08:51.879 - INFO - 5948 - azureml.automl.runtime.featurization.data_transformer.__init__:174 - Feature sweeping enabled: False
2021-03-01 23:08:51.879 - INFO - 5948 - azureml.automl.runtime.featurization.data_transformer.__init__:175 - Feature sweeping timeout: 86400
2021-03-01 23:08:51.883 - CRITICAL - 5948 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: Unclassified
Class: AttributeError
Message: /anaconda/envs/azureml_py36/lib/libxgboost.so: undefined symbol: XGBoosterUnserializeFromBuffer
Traceback:
  File "_model_download_utilities.py", line 174, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))

ExceptionTarget: Unspecified
2021-03-01 23:08:52.117 - CRITICAL - 5948 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: Unclassified
Class: AttributeError
Message: /anaconda/envs/azureml_py36/lib/libxgboost.so: undefined symbol: XGBoosterUnserializeFromBuffer
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "_model_download_utilities.py", line 90, in _download_automl_model
    model = _load_automl_model(model_path)
  File "_model_download_utilities.py", line 174, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))

ExceptionTarget: Unspecified
2021-03-01 23:08:52.118 - INFO - 5948 - azureml.train.automl._model_download_utilities._log_activity:92 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=993.3[ms]
2021-03-01 23:08:52.120 - CRITICAL - 5948 - azureml.train.automl.run.log_traceback:224 - Type: Unclassified
Class: AttributeError
Message: /anaconda/envs/azureml_py36/lib/libxgboost.so: undefined symbol: XGBoosterUnserializeFromBuffer
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 701, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 90, in _download_automl_model
    model = _load_automl_model(model_path)
  File "_model_download_utilities.py", line 174, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))

ExceptionTarget: Unspecified
2021-03-01 23:08:52.121 - INFO - 5948 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=1155.08[ms]
2021-03-01 23:12:14.483 - INFO - 5948 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-03-01 23:12:14.498 - INFO - 5948 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-03-01 23:12:14.503 - INFO - 5948 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2021-03-01 23:12:14.636 - INFO - 5948 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=132.86[ms]
2021-03-01 23:12:14.636 - INFO - 5948 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=138.17[ms]
2021-03-01 23:12:14.636 - INFO - 5948 - azureml.train.automl._model_download_utilities._log_activity:54 - ActivityStarted: DownloadModel
2021-03-01 23:12:15.570 - INFO - 5948 - azureml.automl.runtime.featurization.data_transformer.__init__:174 - Feature sweeping enabled: False
2021-03-01 23:12:15.570 - INFO - 5948 - azureml.automl.runtime.featurization.data_transformer.__init__:175 - Feature sweeping timeout: 86400
2021-03-01 23:12:15.572 - CRITICAL - 5948 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: Unclassified
Class: AttributeError
Message: /anaconda/envs/azureml_py36/lib/libxgboost.so: undefined symbol: XGBoosterUnserializeFromBuffer
Traceback:
  File "_model_download_utilities.py", line 174, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))

ExceptionTarget: Unspecified
2021-03-01 23:12:15.735 - CRITICAL - 5948 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: Unclassified
Class: AttributeError
Message: /anaconda/envs/azureml_py36/lib/libxgboost.so: undefined symbol: XGBoosterUnserializeFromBuffer
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "_model_download_utilities.py", line 90, in _download_automl_model
    model = _load_automl_model(model_path)
  File "_model_download_utilities.py", line 174, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))

ExceptionTarget: Unspecified
2021-03-01 23:12:15.735 - INFO - 5948 - azureml.train.automl._model_download_utilities._log_activity:92 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=1099.41[ms]
2021-03-01 23:12:15.736 - CRITICAL - 5948 - azureml.train.automl.run.log_traceback:224 - Type: Unclassified
Class: AttributeError
Message: /anaconda/envs/azureml_py36/lib/libxgboost.so: undefined symbol: XGBoosterUnserializeFromBuffer
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 701, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 90, in _download_automl_model
    model = _load_automl_model(model_path)
  File "_model_download_utilities.py", line 174, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))

ExceptionTarget: Unspecified
2021-03-01 23:12:15.737 - INFO - 5948 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=1253.84[ms]
2021-03-04 21:43:54.927 - INFO - 6063 - azureml.train.automl.automlconfig._start_execution:211 - Submitting remote.
2021-03-05 00:31:27.242 - INFO - 6063 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-03-05 00:31:27.289 - INFO - 6063 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-03-05 00:31:27.296 - INFO - 6063 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2021-03-05 00:31:27.423 - INFO - 6063 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=126.66[ms]
2021-03-05 00:31:27.423 - INFO - 6063 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=134.23[ms]
2021-03-05 00:31:27.428 - INFO - 6063 - azureml.train.automl._model_download_utilities._log_activity:54 - ActivityStarted: DownloadModel
2021-03-05 00:31:36.208 - INFO - 6063 - azureml.automl.runtime.distributed.utilities.horovod_initialized:58 - Horovod not found in current environment. Distribution via Horovod will be disabled.
2021-03-05 00:31:38.419 - INFO - 6063 - azureml.automl.runtime.featurization.data_transformer.__init__:174 - Feature sweeping enabled: False
2021-03-05 00:31:38.419 - INFO - 6063 - azureml.automl.runtime.featurization.data_transformer.__init__:175 - Feature sweeping timeout: 86400
2021-03-05 00:31:40.014 - CRITICAL - 6063 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: Unclassified
Class: AttributeError
Message: /anaconda/envs/azureml_py36/lib/libxgboost.so: undefined symbol: XGBoosterUnserializeFromBuffer
Traceback:
  File "_model_download_utilities.py", line 174, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))

ExceptionTarget: Unspecified
2021-03-05 00:31:40.094 - CRITICAL - 6063 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: Unclassified
Class: AttributeError
Message: /anaconda/envs/azureml_py36/lib/libxgboost.so: undefined symbol: XGBoosterUnserializeFromBuffer
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "_model_download_utilities.py", line 90, in _download_automl_model
    model = _load_automl_model(model_path)
  File "_model_download_utilities.py", line 174, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))

ExceptionTarget: Unspecified
2021-03-05 00:31:40.094 - INFO - 6063 - azureml.train.automl._model_download_utilities._log_activity:92 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=12666.48[ms]
2021-03-05 00:31:40.095 - CRITICAL - 6063 - azureml.train.automl.run.log_traceback:224 - Type: Unclassified
Class: AttributeError
Message: /anaconda/envs/azureml_py36/lib/libxgboost.so: undefined symbol: XGBoosterUnserializeFromBuffer
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 701, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 90, in _download_automl_model
    model = _load_automl_model(model_path)
  File "_model_download_utilities.py", line 174, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))

ExceptionTarget: Unspecified
2021-03-05 00:31:40.096 - INFO - 6063 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=12853.97[ms]
